version: '3'

services:
  api_metric:
    build: metric
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_HOST: metric
      DB_PORT: 3306
      DB_NAME: mysql
      DB_USERNAME: root
      DB_PASSWORD: root
    restart: always
    depends_on:
      metric:
        condition: service_healthy
  metric:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

    